Digital humanities investigates how digital formats and tools are changing the way we share knowledge in the humanities. This class is an introduction to some of these formats and tools, along with a lot of critical reflection and discussion.

This course will investigate the ways that humanists are using digital tools and digital techniques in their research, and the relationship between those tools and techniques and the information sciences. Not only will the course address the major theoretical themes present in the study of the digital humanities today, it will also give the students the opportunity to gain experience curating, manipulating and visualizing digital data from the humanities and allied social sciences. We will then also investigate different approaches to engaging with data-intensive projects in these fields, including the potential applications of such resources in the educational, library and archival environments

Digital humanities (DH) is the study of culture using digital methods and also the study of digital culture. In digital humanities, we analyze cultural materials and tell stories using digital technologies while maintaining a critical lens.

What is a classroom? What is the relationship between content and learning? What makes one a “digital humanist?” What makes one an ally to the digital humanities? How do we form questions in the humanities that the computer can help us answer? How do digital tools respond to these questions?


## Readings 

Burdick, Anne, Johanna Drucker, Peter Lunenfeld, Todd Presner, and Jeffrey Schnapp. “ 1: Humanities to Digital Humanities.” In *Digital_Humanities* (Cambridge, MA: MIT Press, 2012).

William Franke, “Involved Knowing: On the Poetic Epistemology of the Humanities,” *The European Legacy* 16:4 (2011), 447-467.