# Introduction au cours {.unnumbered}

::: {.content-visible when-format="html" unless-format="revealjs"}

```{=html}
<iframe src="_slides/01a.html"></iframe>
```
[Ouvrir dans mon navigateur](_slides/01a.html){target="_blank"} 

::: 

## Bienvenue ! 

Cette séance est dédiée d'une part à la présentation du cours, son déroulement et autres détails utiles, d'autre part à un (bref) panorama des Humanités Numériques. 

## Tour de table 

Quelques questions :

- Quel est votre prénom ? 
- Quel est votre parcours académique ? 
- Qu’attendez-vous de ce cours ? 
- Que savez-vous des Humanités Numériques ? 

<!-- 
MV: 

Mon nom est Mathilde Verstraete, je suis doctorante au Département de littératures et de langues du monde de l’Université de Montréal. J'ai un parcours en lettres classiques: j'ai donc étudié le latin et le grec ancien avant de me tourner vers les Humanités Numériques. Je suis en rédaction de thèse depuis peu, je suis aussi auxiliaire de recherche à la Chaire de recherche du Canada sur les écritures numériques (dirigée par Marcello Vitali-Rosati), je suis proche des Groupe de recherche sur les éditions critiques en contexte numérique et Centre de recherche interuniversitaire sur les humanités numériques. Je vais avoir beaucoup d’occasions de vous parler des projets sur lesquels nous travaillons dans ces laboratoires.

Je donne ce cours parce qu’il m’a été attribué par le Département de littératures et de langues du monde, je suis très heureuse d’avoir l’occasion de présenter des initiatives et des projets qui me tiennent à cœur et qui sont parfois en lien avec ma thèse. À vous! 

--> 

## Déroulement du cours {.smaller}

- Cours en présentiel = présence requise ; 
- Lectures obligatoires avant chaque séance : 
  - Les lectures qui ne sont pas encore précisées le seront au moins une semaine avant la semaine concernée ; 
  - Les lectures obligatoires serviront de base à des discussions pendant le cours et sont à connaître pour les divers examens ; 
- Support/ressources disponibles à la fin de chaque cours (sur ce site web) : 
  - Ce qui ne dispense aucunement la prise de note durant le cours ; 
- Pendant les séances : partie théorique, manipulations, échanges. 

## Objectifs du cours 

Cf. le [Plan de cours](Plan-Cours.html#objectifs-et-contenu-du-cours). 

## Présentation des séances 

Cf. le [Plan de cours](Plan-Cours.html#calendrier-des-séances-et-des-lectures). 

<!-- 
Est-ce que vous êtes disponibles pour les ateliers IA ?

-->

## Modalités d'évaluation 

Cf. le [Plan de cours](Plan-Cours.html#modalités-dévaluation). 