project:
  output-dir: _book/_slides
  render:
    - index.qmd
    - calendrier.qmd
    - 01a.qmd 
    - 01b.qmd
    - 02.qmd 
    - 03.qmd
    - 04.qmd
    - 05.qmd
    - references.qmd

bibliography: ref.bib

format: 
  revealjs: 
    footer: HNU2000-A25
    theme: ["slides.scss"]
    slide-number: true
    slide-level: 3
#filters: 
#  - relevel_headings.lua