# Plan du cours {.unnumbered} 

- *Sigle du cours* : HNU2000 
- *Titre du cours* : Humanités numériques : technologies 
- *Trimestre* : Automne 2025 
- *Titulaire du cours* : Mathilde Verstraete 
- *Coordonnées* : [mathilde.verstraete@umontreal.ca](mailto:mathilde.verstraete@umontreal.ca)
- *Horaire* : Mardi 08h30-11h30 (du 02/09 au 09/12/2025) 
- *Lieu* : À confirmer 

## Objectifs et contenu du cours 

Les disciplines humanistes au sens large s’appuient de plus en plus sur des outils informatiques pour explorer, traiter, analyser, diffuser leurs objets d’étude. Cette irruption des outils issus des sciences dites dures dans les sciences humaines a donné naissance à un nouveau champ interdisciplinaire, celui dit des humanités numériques.  

L’objectif principal du cours ***HU2000 -- Humanités numériques : technologies*** est de familiariser les étudiant·e·s aux principaux outils, technologies, logiciels, utilisés dans ce champ. Cette familiarisation passera par la manipulation concrète d’outils numériques et par la réalisation de projets pratiques.
 
Parmi les thématiques abordées durant le cours: 

- La connaissance de son ordinateur; 
- L’encodage et la structure de fichiers numériques; 
- Les formats d’écriture; 
- Le versionnement de ses données; 
- Le traitement et la gestion des références bibliographiques; 
- La fouille et l’analyse de textes;  
- La reconnaissance automatique d’écritures manuscrites; 
- La programmation (introduction); 
- etc. 

À l’issue de ce cours, les  étudiant·e·s seront en mesure d’entreprendre, de documenter et de structurer un projet en exploitant les méthodologies des humanités numériques. En outre, les  étudiant·e·s auront développé une capacité critique face aux outils numériques, en comprenant leurs potentiels, leurs limites, et leurs implications dans les pratiques de recherche. 

## Organisation du cours 

Le cours alterna entre théorie et pratique. De manière générale, chaque cours sera l’occasion d’étudier un outil. À cette fin, il sera demandé à l’étudiant⸱e de préparer la séance par une ou des lecture(s) et/ou des manipulations sur son ordinateur personnel  (installation de logiciel, création de compte, etc.). Le cours sera l’occasion d’étudier -- d’un point de vue pratique, mais aussi théorique -- l’outil en question. Il pourra être demandé à l’étudiant⸱e de terminer des manipulations après la séance de cours et pour le cours suivant. 

Il est impératif que l’étudiant⸱e possède un ordinateur. 

## Calendrier des séances et des lectures 

Le cours de cette année sera axé sur le cycle de vie du texte savant en contexte numérique. On abordera le texte source (séances 1-7), son analyse (8-10) et sa publication et diffusion (11-13). 

### [Séance 1 : 02/09] Introduction 

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| [Sinatra, Vitali-Rosati, Histoire des humanités numériques, 2014](https://www.parcoursnumeriques-pum.ca/1-pratiques/chapitre3.html) | Digital Humanities Manifesto 2.0<br>[Underwood, Why an Age of Machine Learning Needs the Humanities](https://www.publicbooks.org/why-an-age-of-machine-learning-needs-the-humanities/) | Présentation du cours<br>Quelques jalons historiques<br>Introduction aux HN (Définitions, Objectifs, Utilisations) | <https://whatisdigitalhumanities.com/> | 

### [Séance 2 : 09/09] CHERCHER: corpus et ressources numériques 

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| TBD | TBD | Bibliothèques numériques, archives ouvertes, écosystèmes des ressources numériques | Moteurs de recherche (+regex?) |

### [Séance 3 : 16/09] ORGANISER: métadonnées et formats 

::: callout-note

[17/09] Date limite pour la modification des choix de cours

:::

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| TBD | TBD | Les différents formats textuels<br>Les traitements *vs* éditeurs de texte | Pandoc | 


<!--
- Le texte et sa saisie 
  - ASCII à Unicode, Mufi 
  - De l'encodage au format 
  - ... 
- Éditeur de texte vs Traitement de Texte
- Point sur le libre 

- Stylo ? 
-->

### [Séance 4 : 23/09] ANNOTER: des *marginalia* à l'annotation numérique 

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| TBD | TBD | Typologie de l’annotation, enjeux collaboratifs, question de la trace | Hypothes.is | 

### [30/09]  

::: callout-note

Congé universitaire -- Journée nationale de la vérité et de la réconciliation

:::

### [Séance 5 : 07/10] REPRÉSENTER le texte (I): formats légers  

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| J. H. Coombs, Allen H Renear, et Steven J DeRose. « Markup Systems and the Future of Scholarly Text Processing » | TBD | Introduction à .txt, .md, .html | Prise en main de Markdown<br>Stylo | 

### [Séance 6 : 14/10] REPRÉSENTER le texte (II): formats riches et normés   

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| LaTeX + Introduction à la TEI | TBD | Baliser son texte | Prise en main de LaTeX (OverLeaf)<br>Observation d'un document en XML-TEI (LeafWriter)<br>Interopérabilité des formats (ekdosis) | 

### [21/10] 

::: callout-note

Semaine de lecture -- pas de cours

:::

### [Séance 7 : 28/10] EXAMEN  

::: callout-important

Examen de mi-session

:::

### [Séance 8 : 04/11] BIBLIOGRAPHIER: citations, identifiants, interopérabilité

::: callout-note

[07/11] Date limite pour l'abandon d'un cours

:::

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| TBD | TBD | BibTeX, CSL | Zotero | 

### [Séance 9 : 11/11] NETTOYER les données textuelles  

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| TBD (data captcha?) | TBD | OCR, HTR, dirty OCR | Introduction à eScriptorium (?) | 

### [Séance 10 : 18/11] ANALYSER: textométrie, stylométrie et TAL 

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| TBD | TBD | Ce que nous disent les mots | Voyant + Notebook Python | 

### [Séance 11 : 25/11] VISUALIER: vers une autre lecture 

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| TBD | [D. Keim et al., « Visual Analytics: Definition, Process, and Challenges »](https://faculty.cc.gatech.edu/~stasko/7450/Papers/keim-va08.pdf)<br>Drucker, [Humanities Approaches to Graphical Display](https://dhq.digitalhumanities.org/vol/5/1/000091/000091.html) | Les différents types de visualisation | TimeLineJS, StoryMapJS | 

### [Séance 12 : 02/12] ÉCRIRE & PUBLIER 

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| TBD | Fauchié,  [The Importance of Single Source Publishing in Scientific Publishing](https://www.digitalstudies.org/article/id/9655/) | Le SSP et les chaînes de publication + introduction à Git | Mise en place d'un workflow éditorial | 

### [Séance 13 : 09/12] IA 

| Lecture obligatoire | Lecture optionnelle | Théorie | Outil | 
| --- | --- | --- | --- | 
| TBD | TBD | Définition, panorama (algorithmes, modèles de langage, IA générative) | Discussion? | 

### [Séance 14 : 16/12] 

::: callout-important

Examen final

:::

## Modalités d'évaluation 

- Participation & Implication dans les exercices et travaux non évalués : 25%; 
- Examen de mi-session (théorie) : 25%
- Examen final (théorie) : 25% 
- Travail final (pratique) : 25% 

L'examen est composé de deux parties : 

1. deux examens écrits, qui consistent en un QCM et des questions ouvertes portant sur la théorie vue en cours et dans les lectures ; 
2.  un travail portant sur la rédaction d'un projet en utilisant au moins deux des outils vus en cours. 

::: callout-tip

## TODO 

Join class prepared to discuss the readings due that day and having explored the tools we will be learning. Plan on expressing your ideas, frustrations, questions, and confusions using your voice during class whenever possible. This is a discussion-based class, so we have the opportunity to delve deeply into issues.

::: 